import { LabelObject } from "./megacorpConstants"

export interface GangType {
  name: string,
  income: string,
  strength: string,
  styles: LabelObject[],
  event: string,
  currentGoal: string,
}

export const gangIncomes = [
  "Assassinations",
  "Black marketing",
  "Blackmail",
  "City gov lobbying",
  "Corp hirelings Cyber trade",
  "Drug production",
  "Drug retail",
  "Extortion",
  "Fraud",
  "Hacking",
  "Horrible vices",
  "Human Trafficking",
  "Merc work",
  "Organlegging",
  "Petty theft",
  "Prostitution",
  "Slave labor",
  "Smuggling",
  "VR production",
]

export const gangStyle = {
  Bestial: { name: "Bestial", description: "favoring an almost feral degree of violence and destruction" },
  Chromed: { name: "Chromed", description: "heavily invested in not-always-safe-or-reliable cyberware" },
  Corporate: { name: "Corporate", description: "with tight discipline and an interest only in the bottom line" },
  Degenerate: { name: "Degenerate", description: "favoring self-destructive enjoyments and decadent indulgences" },
  Doctrinaire: { name: "Doctrinaire", description: " obsessed with an ideology or Great Cause despite all obstacles" },
  Familial: { name: "Familial", description: "with personal ties of blood between most members and all leaders" },
  Flamboyant: { name: "Flamboyant", description: "loving style and display over practicality" },
  Greedy: { name: "Greedy", description: "pushing for more turf and money despite the obvious risks involved" },
  Idealistic: { name: "Idealistic", description: "pretending to a noble cause despite the grubby reality" },
  Nihilistic: { name: "Nihilistic", description: "caring for nothing very much" },
  Pious: { name: "Pious", description: "devoted to a particular fringe religion or cult" },
  Pretentious: { name: "Pretentious", description: "overtly seeing themselves as their turf's government and lawful rulers" },
  Sadistic: { name: "Sadistic", description: "preferring lingering pain and horror over quick violence" },
  Sanctioned: { name: "Sanctioned", description: "operating with the tacit support and approval of city government" },
  Terrifying: { name: "Terrifying", description: "focusing on intimidating and cowing all possible foes with raw terror" },
  Themed: { name: "Themed", description: "devoted to a particular visual or aesthetic theme at all costs" },
  Wretched: { name: "Wretched", description: "impoverished and desperate to attain even basic necessities" },
  Nationalist: { name: "Nationalist", description: "supporting a particular nation" },
  Swarming: { name: "Swarming", description: "favoring masses of low-level gangers over fewer" },
  Technical: { name: "Technical", description: " preferring high-tech tools and expertise" },
}

export const gangStyles = [
  gangStyle.Bestial,
gangStyle.Chromed,
gangStyle.Corporate,
gangStyle.Degenerate,
gangStyle.Doctrinaire,
gangStyle.Familial,
gangStyle.Flamboyant,
gangStyle.Greedy,
gangStyle.Idealistic,
gangStyle.Nihilistic,
gangStyle.Pious,
gangStyle.Pretentious,
gangStyle.Sadistic,
gangStyle.Sanctioned,
gangStyle.Terrifying,
gangStyle.Themed,
gangStyle.Wretched,
gangStyle.Nationalist,
gangStyle.Swarming,
gangStyle.Technical,
]

export const gangStrengths = [
  "They have an elite of cybered pros ",
  "They have close ties with city government ",
  "A local corp is secretly backing them ",
  "The locals genuinely support them ",
  "Their leadership is extremely competent",
  "They have strong gang alliances ",
  "They have a fearsome reputation",
  "They have ties outside the city ",
  "They know secret places in the district ",
  "They have excellent gear and weapons ",
  "They provide a critical district service",
  "A local group views them as protectors ",
  "They're unusually wealthy",
  "They're very selective in their membership",
  "They have a monopoly on something",
  "They have critical blackmail info",
  "They have celebrity members",
  "They have a powerful local patron",
  "They have a web of spies in the area",
  "They're inexplicably lucky"
]

export const gangEvents = [
  "The former leader was recently killed",
  "A splinter group split off from the gang",
  "The cops cracked down on the gang",
  "A corp hired them for some dirty work",
  "They badly lost a fight with another group",
  "They conducted some local terrorism",
  "They stole something very valuable",
  "They got caught in two other gangs' fight",
  "A valuable business began on their turf",
  "Their favorite income was squeezed",
  "A gang lieutenant turned traitor",
  "The gang changed their crime focus",
  "They moved their headquarters",
  "They actually did some legit work",
  "They crushed a rival in a bloody clash",
  "They acquired members with a rare skill",
  "They came into a large cash windfall",
  "They got a lot of loot they can't really use",
  "They recently fell into dire poverty",
  "They acquired a powerful gov patron",
]

export const gangGoals = [
  "Wipe out a competitor for their turf",
  "Expand into an under-defended area",
  "Avenge some slight by another group",
  "Cyber up their enforcers with big iron",
  "Make an alliance with another gang",
  "Persuade a corp to recruit their aid",
  "Crush a bothersome local resister",
  "Recruit more useful talent",
  "Take over a local vice trade",
  "Fence an extremely hot item of value",
  "Regroup after some recent reversal",
  "Resolve a serious leadership conflict",
  "Start up a profitable front business",
  "Make inroads in a new profitable crime",
  "Intimidate the locals with some atrocity",
  "Evade a local police crackdown",
  "Fight off an incursion by another gang",
  "Recover a stolen stash or goods",
  "Tighten their grip on their current turf",
  "Forge a useful new public impression",
]


export const gangNameElements = [
  "Street name ",
  "Color",
  "Violent action",
  "Animal",
  "Direction",
  "Fashion item",
  "Leader's name",
  "Religious figure",
  "Geographic location",
  "District name",
  "Important date",
  "Drug name",
  "Building name",
  "Nation name",
  "Physical trait",
  "Favorite cyber",
  "Intimidating adjective",
  "Weapon",
  "Barbarous habit",
  "The gang's mission",
]

export const gangOrgElements = [
  "Army",
  "Association",
  "Boys/Girls",
  "Brotherhood",
  "Clan",
  "Clique",
  "Company",
  "Crew",
  "Gang",
  "Horde",
  "Mob",
  "Organization",
  "Outfit",
  "Pack",
  "Posse",
  "Ring",
  "Set",
  "Society",
  "Squad",
  "Syndicate",
]