export interface LabelObject {
  name: string,
  description: string
}

export interface MegaCorp {
  name: string,
  focus: string,
  strength: string,
  styles: LabelObject[],
  corpEvent: string,
  currentGoal: string,
}

export enum CorpFocus {
  Agriculture = "Agriculture",
  Computing = "Computing",
  ConsumerGoods = "Consumer Goods",
  DataBrokering = "Data Brokering",
  Education = "Education",
  FinancialServices = "Financial Services",
  MediaEntertainment = "Media/Entertainment",
  Mining = "Mining",
  SecurityServices = "Security Services",
  VehiclesAerospace = "Vehicles/Aerospace",
  Biotech = "Biotech",
  Construction = "Construction",
  Cyberware = "Cyberware",
  Drugs = "Drugs",
  Electronics = "Electronics",
  HeavyIndustry = "Heavy Industry",
  Medical = "Medical",
  PowerGeneration = "Power Generation",
  TransportLogistics = "Transport/Logistics",
  Weaponry = "Weaponry",
}

//each megacorp has one main corp focus
export const corpFoci = [
  CorpFocus.Agriculture,
  CorpFocus.Computing,
  CorpFocus.ConsumerGoods,
  CorpFocus.DataBrokering,
  CorpFocus.Education,
  CorpFocus.FinancialServices,
  CorpFocus.MediaEntertainment,
  CorpFocus.Mining,
  CorpFocus.SecurityServices,
  CorpFocus.VehiclesAerospace,
  CorpFocus.Biotech,
  CorpFocus.Construction,
  CorpFocus.Cyberware,
  CorpFocus.Drugs,
  CorpFocus.Electronics,
  CorpFocus.HeavyIndustry,
  CorpFocus.Medical,
  CorpFocus.PowerGeneration,
  CorpFocus.TransportLogistics,
  CorpFocus.Weaponry,
]

//at least one of these.
export const CorpStyle = {
  Bloodless:{ name:'Bloodless',description:"never reacting out of emotion but always focusing on profit"},
  Brutish:{ name:'Brutish',description:"relying on money and influence to force its products into success"},
  Bureaucratic:{ name:'Bureaucratic',description:"operating on calcified principles and dull, inreflective rules."},
  Cultish:{ name:'Cultish',description:"cultivating a religious kind of isolating devotion in its employees"},
  Decaying:{ name:'Decaying',description:"blinding pursuing products and schemes that just aren't going to work."},
  Dwindling:{ name:'Dwindling',description:"clinging to a product line or service that was once more profitable"},
  Fraudulent:{ name:'Fraudulent',description:"relying on political influence and force to sell its half-functional goods"},
  Haughty:{ name:'Haughty',description:"focusing only on the very top end of its market and product type"},
  Murderous:{ name:'Murderous',description:" making precise and targeted use of violence against its problems"},
  Personalized:{ name:'Personalized',description:"with individual managers having very personal control of branches"},
  Reckless:{ name:'Reckless',description:"constantly making dangerous bets that may or may not pay off"},
  Unreliable:{ name:'Unreliable',description:"its products and tech prone to deniable but very real problems"},
  Vicious:{ name:'Vicious',description:"always preferring loudly overt bloodshed and violence when practical"},
  Esoteric:{ name:'Esoteric',description:" following an aesthetic or set of goals strange to outside observers"},
  Hateful:{ name:'Hateful',description:"as it seems to be largely designed to do horrible things to non-customers"},
  Innovative:{ name:'Innovative',description:"coming up with daring new ideas and products despite the risks"},
  Pandering:{ name:'Pandering',description:"acutely interested in good public relations regardless of its acts"},
  Rapacious:{ name:'Rapacious',description:"always trying to gobble up and assimilate smaller competitors"},
  Spiteful:{ name:'Spiteful',description:"willing to lose money to inflict punishment on its rivals and enemies"},
  Vengeful:{ name:'Vengeful',description:"unusually inclined to punish those who trouble it, even if unprofitable"},
}
export const corpStyles = [
  CorpStyle.Brutish,
  CorpStyle.Cultish,
  CorpStyle.Dwindling,
  CorpStyle.Fraudulent,
  CorpStyle.Haughty,
  CorpStyle.Murderous,
  CorpStyle.Personalized,
  CorpStyle.Reckless,
  CorpStyle.Unreliable,
  CorpStyle.Vicious,
  CorpStyle.Bloodless,
  CorpStyle.Bureaucratic,
  CorpStyle.Decaying,
  CorpStyle.Esoteric,
  CorpStyle.Hateful,
  CorpStyle.Innovative,
  CorpStyle.Pandering,
  CorpStyle.Rapacious,
  CorpStyle.Spiteful,
  CorpStyle.Vengeful,
]

// one corp strength
export enum CorpStrength {
  Rich = "They're even richer than most corps",
  LoyalStaff = "Their low-level staff are zealously loyal",
  BestProduct = "They have the best products of one type",
  EliteOperatives = "They have a stable of elite operatives",
  SecretAgents = "They have plants among many rivals",
  Untouchable = "Other corps are reluctant to touch them",
  EfficientProduct = "Their products are cheap but effective",
  SpecialTech = "They have access to special technology",
  StringMilitary = "Their military forces are surprisingly strong",
  ControlledGood = "They largely control an illegal good",
  HighSecurity = "They have very well-trained security",
  CulturalTies = "They have useful religious or ethnic ties",
  GoodRep = "They have a respected reputation",
  InfoTech = "Their information tech is superb",
  EffectiveSchemes = "Their schemes are unusually effective",
  LocalGovernmentTies = "The local government has strong ties",
  Protectors = "They're viewed as protectors by a group",
  SpyNetwork = "They have a vast web of spies in the city",
  TerritoryControl = "They have absolute rule over an area",
  Lucky = "They're just inexplicably lucky",
}

export const corpStrengths = [
  CorpStrength.Rich,
  CorpStrength.LoyalStaff,
  CorpStrength.BestProduct,
  CorpStrength.EliteOperatives,
  CorpStrength.SecretAgents,
  CorpStrength.Untouchable,
  CorpStrength.EfficientProduct,
  CorpStrength.SpecialTech,
  CorpStrength.StringMilitary,
  CorpStrength.ControlledGood,
  CorpStrength.HighSecurity,
  CorpStrength.CulturalTies,
  CorpStrength.GoodRep,
  CorpStrength.InfoTech,
  CorpStrength.EffectiveSchemes,
  CorpStrength.LocalGovernmentTies,
  CorpStrength.Protectors,
  CorpStrength.SpyNetwork,
  CorpStrength.TerritoryControl,
  CorpStrength.Lucky,
]

// one recent corp event
export enum CorpEvent {
  LosingMoney = "It's losing money with its current products",
  LosingControl = "The CEO is failing or losing control",
  BadRep = "It earned a miserable public reputation",
  Atrocity = "It committed a barely-deniable atrocity",
  UnderAttack = "It's under attack by a strong rival",
  Monopoly = "It crushed almost all its direct competition",
  SpinOff = "It spun off a major subsidiary corp",
  BreakThrough = "It made a great tech breakthrough",
  Empire = "It obtained effective rule of an area",
  IndustryShutDown = "It shut down a vital local industry",
  CivilWar = "A civil war broke out among its branches",
  KingMaker = "It backed a successful rebel government",
  PrBlitz = "It conducted a PR blitz on the city",
  SpecialGovernmentTies = "It formed special ties with the government",
  LostCeo = "Its CEO died or was forced out",
  DrivenOut = "It was driven out of a market recently",
  LocalGovernmentProblems = "It has serious problems with the local gov",
  StretchedThing = "It over-extended itself into new markets",
  BadProduct = "A product recently backfired direly",
  GameOfThrones = "Its execs are trying to kill each other",
}

export const corpEvents = [
  CorpEvent.LosingMoney,
  CorpEvent.LosingControl,
  CorpEvent.BadRep,
  CorpEvent.Atrocity,
  CorpEvent.UnderAttack,
  CorpEvent.Monopoly,
  CorpEvent.SpinOff,
  CorpEvent.BreakThrough,
  CorpEvent.Empire,
  CorpEvent.IndustryShutDown,
  CorpEvent.CivilWar,
  CorpEvent.KingMaker,
  CorpEvent.PrBlitz,
  CorpEvent.SpecialGovernmentTies,
  CorpEvent.LostCeo,
  CorpEvent.DrivenOut,
  CorpEvent.LocalGovernmentProblems,
  CorpEvent.StretchedThing,
  CorpEvent.BadProduct,
  CorpEvent.GameOfThrones,
]

export enum CorpGoal {
  smashRival = "Smash a particular rival corporation",
  researchTech = "Research a revolutionary new tech",
  AcquireResource = "Acquire a new raw material source ",
  MonopolizeProduct = "Monopolize a particular product type",
  InflictPropaganda = "Inflict a PR disaster on a rival",
  PreventDisaster = "Stave off financial disaster with profits",
  PlantMole = "Plant a mole in another corp's C-suite ",
  ExplortResource = "Ruthlessly exploit a resource source ",
  DefameCompetitor = "Defame a competing product line",
  SabotageRival = "Sabotage a rival's current goal",
  ExpandTerritory = "Open a new branch in a hostile area ",
  ExpandMilitary = "Acquire more tangible military power ",
  ForgeRetailChannel = "Forge a new retail channel in an area ",
  ForceMarketOpen = "Force open a currently-closed market ",
  BackTerrorists = "Back a useful group of terrorists",
  StealSecret = "Steal a vital secret from another corp",
  FrameRival = "Frame a rival for an impending disaster",
  CrushUnion = "Crush annoying labor troubles",
  SubvertGovernment = "Subvert an annoying government",
  SpreadIdeal = "Spread a particular corp-serving ideal ",
}
export const corpGoals = [
  CorpGoal.smashRival,
  CorpGoal.researchTech,
  CorpGoal.AcquireResource,
  CorpGoal.MonopolizeProduct,
  CorpGoal.InflictPropaganda,
  CorpGoal.PreventDisaster,
  CorpGoal.PlantMole,
  CorpGoal.ExplortResource,
  CorpGoal.DefameCompetitor,
  CorpGoal.SabotageRival,
  CorpGoal.ExpandTerritory,
  CorpGoal.ExpandMilitary,
  CorpGoal.ForgeRetailChannel,
  CorpGoal.ForceMarketOpen,
  CorpGoal.BackTerrorists,
  CorpGoal.StealSecret,
  CorpGoal.FrameRival,
  CorpGoal.CrushUnion,
  CorpGoal.SubvertGovernment,
  CorpGoal.SpreadIdeal,
]

export enum CorpElement {
  Associates = "Associates",
  Bank = "Bank",
  Bureau = "Bureau",
  Combine = "Combine",
  Community = "Community",
  Corp = "Corp",
  GmbH = "GmbH",
  Guild = "Guild",
  Industries = "Industries",
  International = "International",
  Incorporated = "Incorporated",
  LLC = "LLC",
  Ltd = "Ltd.",
  Products = "Products",
  Sciences = "Sciences",
  Services = "Services",
  Technologies = "Technologies",
  Union = "Union",
  Unity = "Unity",
  Universal = "Universal",
}

export const corpElements = [
  CorpElement.Associates,
  CorpElement.Bank,
  CorpElement.Bureau,
  CorpElement.Combine,
  CorpElement.Community,
  CorpElement.Corp,
  CorpElement.GmbH,
  CorpElement.Guild,
  CorpElement.Industries,
  CorpElement.International,
  CorpElement.Incorporated,
  CorpElement.LLC,
  CorpElement.Ltd,
  CorpElement.Products,
  CorpElement.Sciences,
  CorpElement.Services,
  CorpElement.Technologies,
  CorpElement.Union,
  CorpElement.Unity,
  CorpElement.Universal,
]

export enum NameElement {
  AnimalName = "Animal name",
  AppealingAdjective = "Appealing adjective",
  CityName = "City name",
  Color = "Color name",
  FamilyName = "Family name",
  ForeignPlaceName = "Foreign place name",
  LocalPlaceName = "Local place name",
  MythicFigure = "Mythic figure or god",
  IndustryName = "Name of its industry",
  NationName = "Nation name",
  NaturalDisaster = "Natural disaster",
  NatureFeature = "Natural feature name",
  NaturalPhenomenon = "Natural phenomenon",
  Number = "Number",
  PoliticalGroup = "Political group name",
  Portmanteau = "Portmanteau",
  ProductName = "Product it sells",
  ReligiousTerm = "Religious term",
  RiverName = "River name",
  ServiceType = "Type of service",
}

export const nameElements = [
  NameElement.AnimalName,
  NameElement.AppealingAdjective,
  NameElement.CityName,
  NameElement.Color,
  NameElement.FamilyName,
  NameElement.ForeignPlaceName,
  NameElement.LocalPlaceName,
  NameElement.MythicFigure,
  NameElement.IndustryName,
  NameElement.NationName,
  NameElement.NaturalDisaster,
  NameElement.NatureFeature,
  NameElement.NaturalPhenomenon,
  NameElement.Number,
  NameElement.PoliticalGroup,
  NameElement.Portmanteau,
  NameElement.ProductName,
  NameElement.ReligiousTerm,
  NameElement.RiverName,
  NameElement.ServiceType
]


const animals = [
  "Falcon",
  "Tiger",
  "Lynx",
  "Shark",
  "Panther",
  "Cheetah",
  "Viper",
  "Wolf",
  "Dragon",
  "Raven",
  "Koi",
  "Spider",
  "Lynx",
  "Hawk",
  "Leopard",
  "Phoenix",
  "Python",
  "Eagle",
  "Bear",
  "Serpent",
  "Leopard",
  "Peacock",
  "Jaguar",
  "Eagle",
  "Fox",
  "Owl",
  "Butterfly",
];

const appealingAdjectives = [
  "Innovative",
  "Dynamic",
  "Pinnacle",
  "Ethereal",
  "Vanguard",
  "Zenith",
  "Quantum",
  "Synergetic",
  "Nebula",
  "Celestial",
  "Effulgent",
  "Apex",
  "Harmony",
  "Stellar",
  "Radiant",
  "Epic",
  "Optimal",
  "Prime",
  "Infinite",
  "Elegant",
  "Serene",
  "Empyreal",
  "Resplendent",
  "Majestic",
  "Opulent",
  "Vivid",
  "Effervescent",
  "Sovereign",
  "Pantheon",
  "Astral",
  "Elysian"
];

const cityNames = [
  "Tokyo",
  "Seoul",
  "Shanghai",
  "Berlin",
  "Dubai",
  "Helsinki",
  "Mumbai",
  "Barcelona",
  "Vienna",
  "Sydney",
  "Paris",
  "London",
  "New York",
  "Moscow",
  "Toronto",
  "Copenhagen",
  "Cairo",
  "Rome",
  "Singapore",
  "San Francisco"
];

const colors = [
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Purple",
  "Orange",
  "Pink",
  "Turquoise",
  "Lime",
  "Magenta",
  "Cyan",
  "Amber",
  "Indigo",
  "Teal",
  "Violet",
  "Maroon",
  "Olive",
  "Sapphire",
  "Ruby",
  "Emerald",
  "Cobalt",
  "Orchid",
  "Umbar",
  "Coral"
];

const familyNames = [
  "Harrington",
  "Montague",
  "Everhart",
  "Astor",
  "Pendleton",
  "Winthrop",
  "Fontaine",
  "Abernathy",
  "St. Claire",
  "Ravenscroft",
  "Beauregard",
  "Fitzroy",
  "Somerset",
  "Worthington",
  "Vanderbilt",
  "Kensington",
  "Tanaka",
  "Yamamoto",
  "Suzuki",
  "Chen"
];

const foreignPlaceNames = [
  "Marrakech",
  "Kyoto",
  "Prague",
  "Buenos Aires",
  "Reykjavik",
  "Cape Town",
  "Istanbul",
  "Dubrovnik",
  "Rio de Janeiro",
  "Santorini",
  "Kuala Lumpur",
  "Oslo",
  "Ho Chi Minh City",
  "Auckland",
  "Casablanca",
  "Brasília",
  "Colombo",
  "Cairo",
  "Kyoto",
  "Vienna"
];

const localPlaceNames = [
  "Maplewood",
  "Brookhaven",
  "Greenfield",
  "Meadowview",
  "Pinecrest",
  "Sunset Hills",
  "Hillside Park",
  "Cypress Grove",
  "Harborview",
  "Willowbrook",
  "Sycamore Ridge",
  "Chestnut Hollow",
  "Lakewood Terrace",
  "Oakridge Heights",
  "Riverdale",
  "Highland Park",
  "Cedar Springs",
  "Bayside",
  "Hollygrove",
  "Woodland Hills"
];

const mythicalFigures = [
  "Anansi",
  "Kitsune",
  "Medusa",
  "Quetzalcoatl",
  "Kraken",
  "Athena",
  "Valkyrie",
  "Raijin",
  "Chupacabra",
  "Coyote",
  "Yara-Ma-Yha-Who",
  "Nian",
  "Aswang",
  "Amaterasu",
  "Maui",
  "Huitzilopochtli",
  "Pegasus",
  "Banshee",
  "Kappa",
  "Sphinx"
];

const industries = [
  "Technology",
  "Healthcare",
  "Finance",
  "Manufacturing",
  "Entertainment",
  "Retail",
  "Automotive",
  "Agriculture",
  "Energy",
  "Telecommunications",
  "Hospitality",
  "Education",
  "Construction",
  "Transportation",
  "Biotechnology",
  "Fashion",
  "Media",
  "Pharmaceuticals",
  "Aerospace",
  "Environmental"
];

const nations = [
  "Avalonia",
  "Veridia",
  "Lunaria",
  "Serenora",
  "Astoria",
  "Thundoria",
  "Cascadia",
  "Miragea",
  "Terranova",
  "Elysium",
  "Panthalassa",
  "Solara",
  "Celestria",
  "Equatoria",
  "Zephyria",
  "Aurora",
  "Olympia",
  "Abyssinia",
  "Vespera",
  "Myrtania"
];

const naturalDisasters = [
  "Earthquake",
  "Hurricane",
  "Tornado",
  "Flood",
  "Wildfire",
  "Volcano",
  "Tsunami",
  "Drought",
  "Blizzard",
  "Cyclone",
  "Pyroclast",
  "Heatwave",
  "Avalanche",
  "Asteroid",
  "Thunderstorm",
  "Sandstorm",
  "Flash Flood",
  "Hailstorm",
  "Typhoon",
  "Lightning Strike"
];

const naturalFeatures = [
  "Mountain",
  "Waterfall",
  "Canyon",
  "Cave",
  "Island",
  "Peninsula",
  "Desert Oasis",
  "Rainforest",
  "Glacier",
  "Lagoon",
  "Hot Spring",
  "Cenote",
  "Fjord",
  "Valley",
  "Plateau",
  "Sea Vent",
  "Geyser",
  "Dune",
  "Cliff",
  "Archipelago"
];

const numbers = [
  "1",    // Unity
  "3",    // Trinity
  "7",    // Seven Wonders of the World, Seven Virtues, Seven Deadly Sins
  "8",    // Infinity", Good Luck in Chinese culture
  "9",    // Nine Muses in Greek Mythology, Nine Worlds in Norse Mythology
  "12",   // Twelve Zodiac Signs, Twelve Apostles
  "13",   // Often considered an unlucky number
  "18",   // Symbolizing life in Jewish tradition
  "21",   // Symbol of coming of age in many cultures
  "40",   // Symbolic in many religious traditions, often denoting a period of trial or testing
  "108",  // Considered sacred in Hinduism and Buddhism
  "333",  // Often associated with spirituality and ascended masters
  "666",  // Number of the Beast in Christian tradition
  "777",  // Considered lucky and divine in various cultures
  "1080", // Sacred number in Hinduism and Buddhism
  "144",  // Number of enlightenment in Buddhism
  "613",  // Number of commandments in Judaism
  "786",  // Represents "Bismillah" in Islam
  "999",  // Symbolic of completion or perfection
  "1008", // Considered sacred in Hinduism
];

const politicalGroups = [
  "Libertarian Party",
  "Green Party",
  "Nationalist Movement",
  "Democratic Socialists of America",
  "Tea Party Movement",
  "Pirate Party",
  "National Rifle Association (NRA)",
  "Antifa",
  "Brexit Party",
  "Women's March",
  "Black Lives Matter",
  "Alt-Right",
  "Socialist Workers Party",
  "Freedom Caucus",
  "People for the Ethical Treatment of Animals (PETA)",
  "Extinction Rebellion",
  "League of Women Voters",
  "QAnon",
  "Indivisible",
  "Workers' Party"
];

const portmanteaus = [
  "Brunch",
  "Spork",
  "Smog",
  "Guesstimate",
  "Chillax",
  "Frenemy",
  "Glamping",
  "Motel",
  "Infomercial",
  "Mockumentary",
  "Bromance",
  "Blog",
  "Sitcom",
  "Staycation",
  "Zoodle",
  "Ginormous",
  "Edutainment",
  "Fomo",
  "Globesity",
  "Jeggings"
];


const productNames = [
  "QuantumSync",
  "EcoGlow",
  "PulseWave",
  "ZenBlitz",
  "VistaFlex",
  "HarmonySphere",
  "NexGenCharm",
  "LunarLuxe",
  "CyberGlide",
  "MystiTech",
  "EpicSpark",
  "SolarSculpt",
  "AquaViva",
  "SkyPulse",
  "VortexVista",
  "NovaBurst",
  "EcoHarbor",
  "TechGrove",
  "VividVerve",
  "QuantumQuill"
];

const religiousTerms = [
  "Faith",
  "Grace",
  "Salvation",
  "Redemption",
  "Atonement",
  "Sacrifice",
  "Prayer",
  "Devotion",
  "Repentance",
  "Leviticus",
  "Eucharist",
  "Divine",
  "Blessing",
  "Soul",
  "Spirit",
  "Pilgrim",
  "Covenant",
  "New Light",
  "Karma",
  "Sabbath"
];

const riverNames = [
  "Amazon",
  "Nile",
  "Mississippi",
  "Yangtze",
  "Ganges",
  "Danube",
  "Mekong",
  "Volga",
  "Congo",
  "Colorado",
  "Thames",
  "Yukon",
  "Rhine",
  "Indus",
  "Loire",
  "Tigris",
  "Euphrates",
  "Seine",
  "Murray",
  "Tagus"
];

const serviceTypes = [
  "Consulting",
  "Cleaning",
  "Transportation",
  "Catering",
  "Security",
  "IT Support",
  "Planning",
  "Healthcare",
  "Legal Advice",
  "Finance",
  "Education",
  "Marketing",
  "Web Development",
  "Graphic Design",
  "Fitness Training",
  "SMM",
  "Travel",
  "Photography",
  "Home Renovation",
  "Landscaping"
];

const naturalPhenomena = [
  "Aurora Borealis",
  "Solar Eclipse",
  "Thunderstorm",
  "Tornado",
  "Rainbow",
  "Volcanic Eruption",
  "Earthquake",
  "Tsunami",
  "Meteor Shower",
  "Cyclone",
  "Fog",
  "Waterspout",
  "Avalanche",
  "Sandstorm",
  "Lunar Eclipse",
  "Hailstorm",
  "Magnetic Storm",
  "Geysers",
  "Halos",
  "Monsoon"
];

export const nameElementList = {
  [NameElement.AnimalName]: animals,
  [NameElement.AppealingAdjective]: appealingAdjectives,
  [NameElement.CityName]: cityNames,
  [NameElement.Color]: colors,
  [NameElement.FamilyName]: familyNames,
  [NameElement.ForeignPlaceName]: foreignPlaceNames,
  [NameElement.LocalPlaceName]: localPlaceNames,
  [NameElement.MythicFigure]: mythicalFigures,
  [NameElement.IndustryName]: industries,
  [NameElement.NationName]: nations,
  [NameElement.NaturalDisaster]: naturalDisasters,
  [NameElement.NatureFeature]: naturalFeatures,
  [NameElement.NaturalPhenomenon]: naturalPhenomena,
  [NameElement.Number]: numbers,
  [NameElement.PoliticalGroup]: politicalGroups,
  [NameElement.Portmanteau]: portmanteaus,
  [NameElement.ProductName]: productNames,
  [NameElement.ReligiousTerm]: religiousTerms,
  [NameElement.RiverName]: riverNames,
  [NameElement.ServiceType]: serviceTypes
}